name: Deploy Pizza Menu to Azure Static Web Apps

# Trigger on push to main or pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Static Website
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Step 2: Deploy static content to Azure
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"       # Your files are in repo root
          output_location: "/"    # Serve files from root
